model: 'MiniROAD'
data_name: 'DASHCAM'
task: 'OAD'
loss: 'FOCAL'
metric: 'cAP'
optimizer: 'AdamW'
device: 'cuda'
feature_pretrained: 'kinetics'
root_path: 'D:\project\DashCam\data\dashcam\features'
rgb_type: 'rgb_kinetics_x3d'
flow_type: 'flow_kinetics_x3d'
annotation_type: 'target_perframe'
video_list_path: 'D:\project\DashCam\model\MiniROAD\data_info\video_list.json'
output_path: 'D:\project\DashCam\model\cake\MiniROAD\output_dashcam'
window_size: 128
batch_size: 64 
test_batch_size: 1 
num_epoch: 10 
lr: 0.0001 
weight_decay: 0.05
num_workers: 0
dropout: 0.20
num_classes: 12 # including background
embedding_dim: 2048
hidden_dim: 1024
num_layers: 1
stride: 4
warmup_epoch: 1
warmup_factor: 0.1
warmup_method: 'linear'
no_flow: False
no_rgb: False