model: 'MROAD_P2'
data_name: 'THUMOS'
task: 'OAD_PHASE2'
loss: 'SUPCON_OAD_P2'
metric: 'AP'
optimizer: 'AdamW'
device: 'cuda'
feature_pretrained: 'kinetics'
root_path: 'D:\\project\\DashCam\\data\\thumos14'
rgb_type: 'rgb_kinetics_resnet50'
flow_type: 'flow_kinetics_bninception'
annotation_type: 'target_perframe'
video_list_path: 'data_info/video_list.json'
output_path: './output_phase2'
window_size: 128 
batch_size: 16 
test_batch_size: 1 
num_epoch: 200
lr: 0.0001 
weight_decay: 0.0001
num_workers: 0
dropout: 0.20
num_classes: 22
embedding_dim: 2048
hidden_dim: 1024
num_layers: 1
stride: 4
skip_eval: True
queue_size: 2048
proj_dim: 128
tau: 0.07
boundary_margin: 0
no_flow: False
no_rgb: False
phase1_ckpt: 'D:\project\DashCam\model\MiniROAD\output_phase1\MROAD_P1_THUMOS_3\ckpts\ckpt_epoch_10.pth'