task: 'CONTRASTIVE'
model: 'CONTRASTIVE_MROAD'
data_name: 'THUMOS'
loss: 'CONTRASTIVE'
output_path: './output_contrastive'
device: 'cuda'

# --- DATA PATHS ---
root_path: 'D:/project/DashCam/data/thumos14'
video_list_path: 'data_info/video_list.json'
feature_pretrained: 'kinetics'
rgb_type: 'rgb_kinetics_resnet50'
flow_type: 'flow_kinetics_bninception'
annotation_type: 'target_perframe'

# --- MODEL HYPERPARAMETERS ---
window_size: 128
stride: 4
embedding_dim: 2048
hidden_dim: 1024
num_layers: 1
dropout: 0.2
num_classes: 22
no_rgb: False
no_flow: False
bg_class_idx: 0


# --- CONTRASTIVE PARAMS (NEW) ---
queue_size_per_class: 1024
queue_size: 65536     # K
momentum: 0.999       # m
temperature: 0.07     # T
gen_dropout: 0.25

# --- OPTIMIZER ---
optimizer: 'AdamW'
batch_size: 16
test_batch_size: 16
num_epoch: 50
lr: 0.0001
backbone_lr: 0.0001
weight_decay: 0.0001
num_workers: 0

# --- PRETRAIN ---
pretrained_backbone_path: 'D:\project\DashCam\MiniROAD\THUMOS_Kinetics.pth'