annotation_type: target_perframe
backbone_lr: 0.0001
batch_size: 128
bg_class_idx: 0
data_name: THUMOS_CONTRASTIVE
device: cuda
dropout: 0.2
embedding_dim: 2048
feature_pretrained: kinetics
flow_type: flow_kinetics_bninception
hidden_dim: 1024
loss: CONTRASTIVE_STRICT
lr: 0.0001
mask_ratio: 0.5
model: CONTRASTIVE_MROAD
momentum: 0.999
no_flow: false
no_rgb: false
num_classes: 22
num_epoch: 100
num_layers: 1
num_workers: 4
optimizer: AdamW
output_path: ./output_contrastive
pretrained_backbone_path: /kaggle/input/thumos14/THUMOS_Kinetics.pth
queue_size_per_class: 512
rgb_type: rgb_kinetics_resnet50
root_path: /kaggle/input/thumos14/thumos14/thumos14
stride: 4
task: CONTRASTIVE
temperature: 0.07
test_batch_size: 128
video_list_path: data_info/video_list.json
weight_decay: 0.0001
window_size: 128
