model: 'MiniROAD'
data_name: 'THUMOS'
task: 'OAD'
loss: 'FOCAL'
metric: 'AP'
optimizer: 'AdamW'
device: 'cuda'
feature_pretrained: 'kinetics'
root_path: 'D:\project\DashCam\data\thumos14'
rgb_type: 'rgb_kinetics_resnet50'
flow_type: 'flow_kinetics_bninception'
annotation_type: 'target_perframe'
video_list_path: 'data_info/video_list.json'
output_path: './output_cls'
window_size: 128 
batch_size: 16 
test_batch_size: 1
num_epoch: 10 
lr: 0.0001 
weight_decay: 0.05
num_workers: 0
dropout: 0.5
num_classes: 21
embedding_dim: 2048
hidden_dim: 1024
num_layers: 1
stride: 4
no_flow: False
no_rgb: False
#contrastive_path: 'D:\project\Cake\MiniROAD\best_model.pth'
freeze_backbone: False
bg_class_idx: 0
warmup_epoch: 1
warmup_factor: 0.1
warmup_method: 'linear'