model: 'MiniROAD'
data_name: 'TVSERIES'
task: 'OAD'
loss: 'FOCAL'
metric: 'cAP'
optimizer: 'AdamW'
device: 'cuda'
feature_pretrained: 'kinetics'
root_path: 'D:\project\DashCam\data\tvseries_2'
rgb_type: 'rgb_kinetics_x3d'
flow_type: 'flow_kinetics_x3d'
annotation_type: 'target_perframe'
video_list_path: 'data_info/video_list.json'
output_path: './output_cls'
window_size: 128
batch_size: 64 
test_batch_size: 1 
num_epoch: 100 
lr: 0.0001 
weight_decay: 0.05
num_workers: 0
dropout: 0.20
num_classes: 31 # including background
embedding_dim: 2048
hidden_dim: 1024
num_layers: 1
stride: 4
warmup_epoch: 1
warmup_factor: 0.1
warmup_method: 'linear'
focal_alpha: 0.5
contrastive_path: 'C:\Users\hieuh\Downloads\tvseries_22.50.pth'
freeze_backbone: True
bg_class_idx: 0